### ISSUE TITLE
RocksDB: No locks available

### ISSUE THREAD

**Issue by bt** [adplabs/unicorn#1]
I'm trying to test Unicorn with RocksDB but the example doesn't seem to work:

``````
$ ./bin/unicorn

                        . . . .
                        ,`,`,`,`,
  . . . .               `\`\`\`\;
  `\`\`\`\`,            ~|;!;!;\!
   ~\;\;\;\|\          (--,!!!~`!       .
  (--,\\\===~\         (--,|||~`!     ./
   (--,\\\===~\         `,-,~,=,:. _,//
    (--,\\\==~`\        ~-=~-.---|\;/J,       Welcome to the Unicorn Database
     (--,\\\((```==.    ~'`~/       a |         BigTable, Document and Graph
       (-,.\\('('(`\\.  ~'=~|     \_.  \              Full Text Search
          (,--(,(,(,'\\. ~'=|       \\_;>
            (,-( ,(,(,;\\ ~=/        \                  Haifeng Li
            (,-/ (.(.(,;\\,/          )             ADP Innovation Lab
             (,--/,;,;,;,\\         ./------.
               (==,-;-'`;'         /_,----`. \
       ,.--_,__.-'                    `--.  ` \
      (='~-_,--/        ,       ,!,___--. \  \_)
     (-/~(     |         \   ,_-         | ) /_|
     (~/((\    )\._,      |-'         _,/ /
      \\))))  /   ./~.    |           \_\;
   ,__/////  /   /    )  /
    '===~'   |  |    (, <.
             / /       \. \
           _/ /          \_\
          /_!/            >_\

  Welcome to Unicorn Shell; enter ':help<RETURN>' for the list of commands.
  Type ":quit<RETURN>" to leave the Unicorn Shell
  Version 2.1.0, Scala 2.11.7, SBT 0.13.8, Built at 2016-07-04 03:42:14.238
===============================================================================

unicorn> var db = Unibase(RocksDB.create("./storage"))
db: unicorn.unibase.Unibase[unicorn.bigtable.rocksdb.RocksTable] = unicorn.unibase.Unibase@615091b8
unicorn> db.createTable("worker")
org.rocksdb.RocksDBException: IO error: lock ./storage/unicorn_meta_table/LOCK: No locks available
  at org.rocksdb.RocksDB.open(Native Method)
  at org.rocksdb.RocksDB.open(RocksDB.java:229)
  at unicorn.bigtable.rocksdb.RocksTable.open(RocksTable.scala:49)
  at unicorn.bigtable.rocksdb.RocksTable.<init>(RocksTable.scala:54)
  at unicorn.bigtable.rocksdb.RocksDB.apply(RocksDB.scala:39)
  at unicorn.bigtable.rocksdb.RocksDB.apply(RocksDB.scala:32)
  at unicorn.unibase.Unibase.createTable(Unibase.scala:98)
  ... 42 elided
``````

Am I doing something wrong?

**Comment by haifengl** [comment]
Thanks! Can  you please try the master branch? After cloning the project, just type ./unicorn.sh in the project directory to start the shell. BTW, can you please use the following fork

https://github.com/haifengl/unicorn

which usually has the latest commits. Thanks!

**Comment by bt** [comment]
Hi @haifengl,

Thanks for the reply and the suggestion! It works perfectly now 😄
